server:
  port: 8782
management: 
  security: 
    enabled: false #关闭安全认证
  port: 8088
  context-path: /monitor
spring:
  http: 
    encoding: 
      charset: UTF-8 #http请求的字符编码
  application: 
    name: ser
  datasource: 
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/console
    username: root
    password: 123456
  jpa: 
    hibernate: 
      ddl-auto: update
    show-sql: true
entitymanager: 
  packagesToScan: org.console
hibernate: 
  dialect: org.hibernate.dialect.MySQL5Dialect #指定数据库方言
  hbm2dll: 
    auto: update #设置使用Hibernate的自动建表方式
logging:
  level:
    root: info
redis: 
  host:127.0.0.1 
  password: 123456